### ISSUE TITLE
Latest package not on NPM

### ISSUE THREAD

**Issue by freshollie** [Osterjour/line-by-line#19]
Hi, 

I don't know if you own the right to be able to update the package on NPM, but your latest commits including 126bb11300cb207c8355372853cc1691d6857a07 are seriously needed on the NPM platform as their bugs are very noticeable.

I found this repository through here: https://www.npmjs.com/package/line-by-line

So I assume you have the right to update the package.

For now I have manually added the source to my project.

**Comment by faizan-ali-ck** [comment]
+1

**Comment by CExDJiang** [comment]
+1

**Comment by Osterjour** [comment]
Done: https://www.npmjs.com/package/line-by-line
