### ISSUE TITLE
After about 1.4M lines I hit memory issues

### ISSUE THREAD

**Issue by OmgImAlexis** [Osterjour/line-by-line#3]
Even though this library claims it doesn't load the file into memory there is either a memory leak or it **IS** loading the file into memory. I'm trying to parse a 7M+ line file going line by line and then inserting it into a mongdb database. I tried this a few times and each time nodejs exited and told me there was a memory issue.

I ended up doing something like this without the library and I'm not getting a single memory issue.
When I used my method I was getting at most 1MB of extra RAM being used compared to IDLE and I'm pretty sure that's just the mongodb connection.
Using your library I was hitting 130MB - 200MB of RAM. When I first open node with my project I sit on about 70MB of RAM on IDLE.

```
var fs = require('fs'),
    es = require("event-stream");

var lineNumber = 1;

var s = fs.createReadStream('import.txt').pipe(es.split()).pipe(es.mapSync(function(line){
    // pause the readstream
    s.pause();

    lineNumber += 1;

    (function(){
        // Run my line by line code here
        // resume the readstream
        s.resume();
    });
}).on('error', function(){
    console.log('Error while reading file.');
}).on('end', function(){
    console.log('Read entirefile.');
}));
```

**Comment by Osterjour** [comment]
Thanks for that!
Do you have some example code about how you implemented the module in your code? Right now I can't reproduce the issue you're seeing.

**Comment by OmgImAlexis** [comment]
I'm not exactly sure as I didn't commit anything into git until I got it working which was after I had switched to a native library as I said above. It would have been something like this.

```
var lineByLineReader = require('line-by-line'),
    lr = new lineByLineReader('import.txt');

lr.on('error', function(err) {
    console.log('Error while reading file.');
});

lr.on('line', function(line) {
    line = line.split('|');
    Category.findOne({
        $or: [
           { 'title': new RegExp(line[2], 'i') },
           { 'aliases': new RegExp(line[2], 'i') }
        ]
    }).exec(function(err, category){
        if(err) {console.log(err);}
        if(category){
            Torrent.create({
                title: line[1],
                category: category._id,
                size: line[5],
                details: [
                    line[3]
                ],
                swarm: {
                    seeders: line[8],
                    leechers: line[9]
                },
                lastmod: Date.now(),
                imported: Date.now(),
                infoHash: line[0]
            }, function(err, torrent) {
                if(err) {
                    if(err.code !== 11000){
                        console.log(err);
                    }
                } else {
                    console.log(torrent.infoHash + ' added');
                }
            });
        }
    });
});

lr.on('end', function() {
     console.log('Read entire file.');
});
```

**Comment by ghost** [comment]
Hm, I'm having the same issue too.  I think I've found what the problem is - the pause and resume functionality.  This simple code causes the memory leak.

``` javascript
lr.on('line', function (line) {
    lr.pause();
    lr.resume();
    return;
});
```

**Comment by ralfschiffert** [comment]
This is also my experience. I have a file with 10MM lines and it just stops after a while. Around 1.3 Million entries. I also removed the pause and resume in an attempt to get down to the issue. It's currently running and I will report back if it fixed it.

**Comment by trvbr** [comment]
@ralfschiffert Curious, did removing pause/resume fix it?

**Comment by ralfschiffert** [comment]
It didn't. I changed to some other approach but don't recall anymore what I did. Different module I think.

On May 22, 2016, at 21:40, Travis Bernard <notifications@github.com<mailto:notifications@github.com>> wrote:

@ralfschifferthttps://github.com/ralfschiffert Curious, did removing pause/resume fix it?

##

**Comment by Osterjour** [comment]
Switching over to this should be easy: https://www.npmjs.com/package/linebyline
I'm actually thinking about deprecating this module and tell everybody to use the other one (which has some nice additional features)
