### ISSUE TITLE
Event end doest work....

### ISSUE THREAD

**Issue by lopezchr** [Osterjour/line-by-line#8]
When the csv is too large and the "end" event is dispatched, all rows have been not readed. It is like the "end" event was triggered before all "line" event has been dispatched and readed. 

The code bellow returns the number of lines of a file. I tested a file with 1500 lines.

``` javascript
   let linesCounter = function(path) {
        return function(callback){ 
            let lr = new LineByLineReader(path)
            let count = 0
            lr.on('line', function(line) {  
                count ++
            })

            lr.on('end', function () {
                callback(null,count)
            })
        }
    }
```

The result was 1423 lines.
I am using the version 0.1.4

**Comment by gogson** [comment]
that was fixed in 0.1.5 see #6
