### ISSUE TITLE
UTF-8 byte order marker not suppressed

### ISSUE THREAD

**Issue by edtguy** [Osterjour/line-by-line#9]
line-by-line works very well, but I've noticed that the value returned for the first line read from the file begins with a special character. Each line of my file is a json object. When I invoke JSON.parse(line), it fails on the first line. I inserted a blank line as the first line of the file, and set skipEmptyLines: true. It did not interpret this line as empty, and generated the following error:

23 Sep 13:35:53 - line: 1 error: [SyntaxError: Unexpected token o]
23 Sep 13:35:53 - bad line: o;?

This is that bit of code inside the on.('line' function:
`try {
       line_obj = JSON.parse(line);
      }
      catch (err) {
        util.log('line:',counter,'error:',err);
        util.log('bad line:',line);
        return;
      }
`
Is there a work-around to avoid this initial character or characters?
Thanks.

**Comment by edtguy** [comment]
Follow-up. Those characters are actually in the file. Apparently, they are an explicit byte order marker pattern (hex EF BB BF) for a UTF-8 file. line-by-line is processing them as part of the actual file contents. Shouldn't line-by-line recognize them as metadata, and strip them out?

**Comment by Osterjour** [comment]
Well that's something which depends on your use case if the module should strip them out. Somebody might want to have/see them in the result?

**Comment by Osterjour** [comment]
Closing this as I still think this should be up to the script that is actually using line-by-line and this module shouldn't change anything.
